### ISSUE TITLE
import ctypes error in IronPython at linux

### ISSUE THREAD

**Issue by njwangwei** [IronLanguages/main#1301] opened 2016-06-21 09:11 UTC
ironpython version is 2.7.6a0；mono is 4.0,os is centos7.0; when I execute from ctypes import *;

>>> from ctypes import *           
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/IronPython-2.7.5/Lib/ctypes/__init__.py", line 441, in <module>
  File "/usr/local/IronPython-2.7.5/Lib/ctypes/__init__.py", line 353, in __init__
OSError: IronPython.Runtime.Exceptions.OSException: cannot load library 
  at IronPython.Modules.CTypes.LoadLibrary (System.String library, Int32 mode) <0x410f5670 + 0x000ab> in <filename unknown>:0 
  at IronPython.Modules.CTypes.dlopen (System.String library, Int32 mode) <0x410f5640 + 0x00013> in <filename unknown>:0 
  at Microsoft.Scripting.Interpreter.FuncCallInstruction`3[T0,T1,TRet].Run (Microsoft.Scripting.Interpreter.InterpretedFrame frame) <0x410f5510 + 0x000b5> in <filename unknown>:0 
  at Microsoft.Scripting.Interpreter.Interpreter.Run (Microsoft.Scripting.Interpreter.InterpretedFrame frame) <0x40578740 + 0x000be> in <filename unknown>:0 

the code at line 441 :

cdll = LibraryLoader(CDLL)
pydll = LibraryLoader(PyDLL)
if _os.name in ("nt", "ce"):
    pythonapi = PyDLL("python dll", None, _sys.dllhandle)
elif _sys.platform == "cygwin":
    pythonapi = PyDLL("libpython%d.%d.dll" % _sys.version_info[:2])
else:
    pythonapi = PyDLL(None)  //here is line 441

**Comment by slide** [comment] 2016-07-10 14:27
Can you provide a reproduction case?

**Comment by slide** [comment] 2016-08-01 18:47
This seems to be an error in the way that the pythonapi is being loaded on non-Windows systems. May need to bypass this for sys.platform == 'cli'

**Comment by slide** [comment] 2016-10-06 02:25
Fixed via #1461

**Closed by slide** 2016-10-06 02:25 UTC
