### ISSUE TITLE
IronPython.Modules.Wpf.LoadComponent broken

### ISSUE THREAD

**Issue by mjdoell** [IronLanguages/main#1273] opened 2016-01-20 00:10 UTC
IronPython.Modules.Wpf.LoadComponent requires a CodeContext as the first argument and unlike other functions that require a CodeContext, an error is thrown if it is not explicitly provided.

This is a recent change, with previous versions of IronPython functioning correctly.

It is possible to work around this by explicitly building a CodeContext, which seems convoluted:

for example:
public object LoadComponent(object self, string filename)
{
  PythonContext cxt = (PythonContext)Microsoft.Scripting.Hosting.Providers.HostingHelpers.GetLanguageContext(m_engine);
  PythonDictionary dict = new PythonDictionary();
  ModuleContext modctx = new ModuleContext(dict, cxt);
  var context = new CodeContext(dict, modctx);
  object result = Wpf.LoadComponent(context, self, filename);
  return result;
}

**Comment by slide** [comment] 2016-01-20 00:57
From looking at LoadComponent, it has always required a CodeContext, unless you are calling it from Python, in which case a CodeContext would be provided automatically.

**Comment by mjdoell** [comment] 2016-01-20 07:10
Thanks for following up!   the issue I'm observing is that the code context is not being provided automatically when calling it from python.  It used to function(I don't have the functional version on hand for ease of reference) , but recently started giving an error saying that 3 arguments were expected. 

Sent from my Bell Sony device over Canada’s largest network.

---- Alex Earl wrote ----

**Comment by slide** [comment] 2016-01-20 12:41
Can you show your Python code?

**Comment by mjdoell** [comment] 2016-01-20 16:55
import sys
print sys.version #Outputs: 2.7.6a0 (IronPython 2.7.6a0 (2.7.6.0) on .NET 4.0.30319.42000 (64-bit))
import clr
clr.AddReference("IronPython.Wpf")
from IronPython.Modules import Wpf as wpf
wpf.LoadComponent("E:\\UI.xaml") #This returns error: TypeError: LoadComponent() takes exactly 3 arguments (1 given)
wpf.LoadComponent(self, "E:\\UI.xaml") #This returns error: TypeError: LoadComponent() takes exactly 3 arguments (2 given)
#self is the class containing this code snipit..
#"E:\\UI.xaml" is the wpf xaml file

**Comment by slide** [comment] 2016-01-20 17:00
I'm pretty sure you should do this:

```python
# if this doesn't work, then you should add the reference as you do now
import wpf 

wpf.LoadComponent(r"E:\UI.xaml")
```

**Comment by simplicbe** [comment] 2016-01-21 08:01
You are using the module "wrong". You should never import modules like this (`from IronPython.Modules import Wpf as wpf`), when they are written as IronPython modules in c#. This is the fact, when the `PythonModule` attribute is used:

```
[assembly: PythonModule("wpf", typeof(IronPython.Modules.Wpf))]
```

If a module is defines like this, you have to import it like:

```
import wpf # As you can see in the module definition "wpf"
```

Otherwise it is not a IronPython module and `PythonContext` will not be passed automatically, which cause your problem.

So you should use it as slide said.

Hope this simple explanation helps.

**Comment by mjdoell** [comment] 2016-01-21 21:21
Thanks for the feedback so far!  I did not know about the PythonModule.

The problem remains, however, and the root of the problem seems to be:
import clr
clr.AddReference("IronPython.Wpf")
import wpf #<-- ImportError: No module named wpf 

I'm describing a (convoluted) work-around below, however the real goal is to understand how to debug/fix "import wpf"

```python
###############################################################################
#
# confirm IronPython version
#
###############################################################################
import sys
print sys.version #<-- 2.7.6a0 (IronPython 2.7.6a0 (2.7.6.0) on .NET 4.0.30319.42000 (64-bit))


###############################################################################
#
# dynamically gernate c# assembly to provide work-around wpf functionality
#
###############################################################################
cSharpSource = """
using System;

using IronPython.Hosting;
using IronPython.Runtime.Types;
using IronPython.Modules;
using IronPython.Runtime.Exceptions;
using IronPython.Runtime.Operations;

using Microsoft.Scripting;
using Microsoft.Scripting.Hosting;

public static class WpfHelper
{
	public static object LoadComponent(object self, string filename)
	{
		Microsoft.Scripting.Hosting.ScriptRuntime runtime = IronPython.Hosting.Python.CreateRuntime();
		Microsoft.Scripting.Hosting.ScriptEngine engine = runtime.GetEngine("py");
	    IronPython.Runtime.PythonContext cxt = (IronPython.Runtime.PythonContext)Microsoft.Scripting.Hosting.Providers.HostingHelpers.GetLanguageContext(engine);
	    IronPython.Runtime.PythonDictionary dict = new IronPython.Runtime.PythonDictionary();
	    IronPython.Runtime.ModuleContext modctx = new IronPython.Runtime.ModuleContext(dict, cxt);
	    IronPython.Runtime.CodeContext context = new IronPython.Runtime.CodeContext(dict, modctx);
	
	    object result = IronPython.Modules.Wpf.LoadComponent(context, self, filename);
	    return result;
	}
}
"""
import Microsoft
import System
import clr
compilerParams = System.CodeDom.Compiler.CompilerParameters()
compilerParams.GenerateInMemory = True
compilerParams.ReferencedAssemblies.Add( r"E:\wpf\IronPython-2.7.3\DLLs\IronPython.Wpf.dll" )
compilerParams.ReferencedAssemblies.Add( r"E:\wpf\IronPython-2.7.3\IronPython.dll" )
compilerParams.ReferencedAssemblies.Add( r"E:\wpf\IronPython-2.7.3\IronPython.Modules.dll" )
compilerParams.ReferencedAssemblies.Add( r"E:\wpf\IronPython-2.7.3\Microsoft.Scripting.dll" )
compilerParams.ReferencedAssemblies.Add( r"E:\wpf\IronPython-2.7.3\Microsoft.Dynamic.dll" )
compilerParams.ReferencedAssemblies.Add( r"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll")
compilerParams.ReferencedAssemblies.Add( r"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xaml.dll")
compilerParams.ReferencedAssemblies.Add( r"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.XML.dll")
provider = Microsoft.CSharp.CSharpCodeProvider()
compileCSharp = provider.CompileAssemblyFromSource(compilerParams, cSharpSource)
for error in compileCSharp.Errors:
	print error
clr.AddReference( compileCSharp.CompiledAssembly )
import WpfHelper #<-- this provides a work-around for broken wpf.LoadComponent functionality


###############################################################################
#
# import assemblies required for WPF in IronPython
#
###############################################################################
from System.Windows import Window
import clr
clr.AddReference("IronPython.Wpf")
#import wpf #<-- ImportError: No module named wpf 
from IronPython.Modules import Wpf as wpf #work-around to reference wpf

###############################################################################
#
# python class to utilize xaml for ui
#
###############################################################################
#Creating the UI for the script
#UI is a subclass of Window
class UI(Window):
	def __init__(self):
		#wpf.LoadComponent(self, r"e:\wpf\ui.xaml") #<-- TypeError: LoadComponent() takes exactly 3 arguments (2 given)
		WpfHelper.LoadComponent(self, r"e:\wpf\ui.xaml")
		self.textbox.Text = "hello!"

win = UI()
win.Show()


###############################################################################
#
# Contents of: ui.xaml
#
###############################################################################
"""
<Window
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    Title="UI" Height="128" Width="256">
    <TextBox x:Name="textbox"  Width="200" />
</Window>
"""

**Comment by slide** [comment] 2016-01-21 22:14
Did you try without the clr.AddReference?

**Comment by mjdoell** [comment] 2016-01-23 00:10
@slide I did try it without clr.AddReference and it returns an error: ImportError: No module named wpf

**Comment by simplicbe** [comment] 2016-01-23 08:31
Place the dll at the ssme location as your ipy.exe. Or in general, your hosting application.

**Comment by slide** [comment] 2016-07-10 14:30
Was this ever resolved?

**Comment by simplicbe** [comment] 2016-07-15 06:57
Tried a lot, can't reproduce this issue. Please reopen if required. Please also try the newest versions which will be released in the next weeks (beta/rc/final).

**Closed by simplicbe** 2016-07-15 06:57 UTC
Labels: untriaged
