### ISSUE TITLE
Cannot run on Ubuntu 16.04 Mono

### ISSUE THREAD

**Issue by ghost** [IronLanguages/main#1454] opened 2016-10-03 16:11 UTC
00:00:36:mono IronPython/ipy64.exe
Traceback (most recent call last):
  File "/media/psf/WinExe/IronPython/Lib/site.py", line 552, in <module>
  File "/media/psf/WinExe/IronPython/Lib/site.py", line 534, in main
  File "/media/psf/WinExe/IronPython/Lib/site.py", line 266, in addusersitepackages
  File "/media/psf/WinExe/IronPython/Lib/site.py", line 241, in getusersitepackages
  File "/media/psf/WinExe/IronPython/Lib/site.py", line 231, in getuserbase
  File "/media/psf/WinExe/IronPython/Lib/sysconfig.py", line 522, in get_config_var
  File "/media/psf/WinExe/IronPython/Lib/sysconfig.py", line 474, in get_config_vars
  File "/media/psf/WinExe/IronPython/Lib/sysconfig.py", line 358, in _init_posix
ImportError: No module named _sysconfigdata
IronPython 2.7.6.3 (2.7.6.3) on Mono 4.0.30319.42000 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.

> > > quit()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > TypeError: str is not callable
> > > 
> > > Killed

00:00:59:

**Comment by slide** [comment] 2016-10-03 16:57
This is a duplicate of #1386

**Closed as completed by slide** 2016-10-03 16:57 UTC
