### ISSUE TITLE
StackOverflowException while iterating dynamic members

### ISSUE THREAD

**Issue by lafrank** [IronLanguages/main#1356] opened 2016-08-25 06:18 UTC
In my effort to do some reflection like parsing of dynamic objects, I wrote the below method:

``` c#
internal protected void ParseDynamicMetaObjectProviderMembers(string varName, dynamic varValue, ref List<DynamicMemberInfo> memberList)
{
  var target = varValue as IDynamicMetaObjectProvider;
  var members = target.GetMetaObject(System.Linq.Expressions.Expression.Constant(target)).GetDynamicMemberNames();

  foreach (var thisMember in members)
  {
    // do something
```

This code actually works perfectly most of the time. But there are certain cases when I encounter a StackOverflowException as soon as executing foreach statement, so I guess there is an issue with the underlying iterator.
Stack seems to fill up with repeating calls in IronPython.Rutime as shown below:

_IronPython.dll!IronPython.Runtime.Types.PythonType.TryGetCustomDir(IronPython.Runtime.CodeContext context, object self)
 IronPython.dll!IronPython.Runtime.Types.PythonType.GetMemberNames(IronPython.Runtime.CodeContext context, object self)
 IronPython.dll!IronPython.Runtime.Binding.MetaUserObject.<GetDynamicMemberNames>d__0.MoveNext()
 IronPython.dll!IronPython.Runtime.List.extend(object seq)
 IronPython.dll!IronPython.Runtime.List.List(object sequence)
 IronPython.dll!IronPython.Runtime.Operations.InstanceOps.DynamicDir(IronPython.Runtime.CodeContext context, System.Dynamic.IDynamicMetaObjectProvider self)
 [Lightweight Function]
 IronPython.dll!IronPython.Runtime.Types.PythonType.TryGetCustomDir(IronPython.Runtime.CodeContext context, object self)
 IronPython.dll!IronPython.Runtime.Types.PythonType.GetMemberNames(IronPython.Runtime.CodeContext context, object self)
 IronPython.dll!IronPython.Runtime.Binding.MetaUserObject.<GetDynamicMemberNames>d__0.MoveNext()
 IronPython.dll!IronPython.Runtime.List.extend(object seq)
 IronPython.dll!IronPython.Runtime.List.List(object sequence)
 IronPython.dll!IronPython.Runtime.Operations.InstanceOps.DynamicDir(IronPython.Runtime.CodeContext context, System.Dynamic.IDynamicMetaObjectProvider self)
 [Lightweight Function]
 IronPython.dll!IronPython.Runtime.Types.PythonType.TryGetCustomDir(IronPython.Runtime.CodeContext context, object self)
 IronPython.dll!IronPython.Runtime.Types.PythonType.GetMemberNames(IronPython.Runtime.CodeContext context, object self)
 IronPython.dll!IronPython.Runtime.Binding.MetaUserObject.<GetDynamicMemberNames>d__0.MoveNext()
 IronPython.dll!IronPython.Runtime.List.extend(object seq)
 IronPython.dll!IronPython.Runtime.List.List(object sequence)
 IronPython.dll!IronPython.Runtime.Operations.InstanceOps.DynamicDir(IronPython.Runtime.CodeContext context, System.Dynamic.IDynamicMetaObjectProvider self)
 [Lightweight Function]
 IronPython.dll!IronPython.Runtime.Types.PythonType.TryGetCustomDir(IronPython.Runtime.CodeContext context, object self)
 IronPython.dll!IronPython.Runtime.Types.PythonType.GetMemberNames(IronPython.Runtime.CodeContext context, object self)
 IronPython.dll!IronPython.Runtime.Binding.MetaUserObject.<GetDynamicMemberNames>d__0.MoveNext()
 IronPython.dll!IronPython.Runtime.List.extend(object seq)
 IronPython.dll!IronPython.Runtime.List.List(object sequence)
 IronPython.dll!IronPython.Runtime.Operations.InstanceOps.DynamicDir(IronPython.Runtime.CodeContext context, System.Dynamic.IDynamicMetaObjectProvider self)
 [Lightweight Function]
 IronPython.dll!IronPython.Runtime.Types.PythonType.TryGetCustomDir(IronPython.Runtime.CodeContext context, object self)
 IronPython.dll!IronPython.Runtime.Types.PythonType.GetMemberNames(IronPython.Runtime.CodeContext context, object self)
 IronPython.dll!IronPython.Runtime.Binding.MetaUserObject.<GetDynamicMemberNames>d__0.MoveNext()
 IronPython.dll!IronPython.Runtime.List.extend(object seq)
 IronPython.dll!IronPython.Runtime.List.List(object sequence)
 IronPython.dll!IronPython.Runtime.Operations.InstanceOps.DynamicDir(IronPython.Runtime.CodeContext context, System.Dynamic.IDynamicMetaObjectProvider self)
 [Lightweight Function]
 IronPython.dll!IronPython.Runtime.Types.PythonType.TryGetCustomDir(IronPython.Runtime.CodeContext context, object self)
 IronPython.dll!IronPython.Runtime.Types.PythonType.GetMemberNames(IronPython.Runtime.CodeContext context, object self)
 IronPython.dll!IronPython.Runtime.Binding.MetaUserObject.<GetDynamicMemberNames>d__0.MoveNext()
 IronPython.dll!IronPython.Runtime.List.extend(object seq)
 IronPython.dll!IronPython.Runtime.List.List(object sequence)
 IronPython.dll!IronPython.Runtime.Operations.InstanceOps.DynamicDir(IronPython.Runtime.CodeContext context, System.Dynamic.IDynamicMetaObjectProvider self)
 [Lightweight Function]_

...

Am I doing something illegitim, or is it an issue in IronPython ?

To be more precise on the cirucumstances of the issue, I am trying to enumerate objects in a module and parse the members of the object. Like a catalogue. As I metioned this works most of the time, but for instance exhibits the issue for UserString module's UserString class, or ZipFile module's ZipExtFile class. But only those.

**Comment by kunom** [comment] 2016-09-10 16:46
This looks to me like a duplicate of #1100.

**Comment by lafrank** [comment] 2016-09-13 10:39
yes, looks pretty much the same

**Comment by slide** [comment] 2017-06-09 14:44
Closing as a duplicate

**Closed as completed by slide** 2017-06-09 14:44 UTC
