### ISSUE TITLE
ImportError exception not thrown on import error

### ISSUE THREAD

**Issue by fdanny** [IronLanguages/main#1205] opened 2015-06-03 03:49 UTC
I am running trying to get the requests to work and I received the following error. The code below is expected to throw an ImportError since the module doesn't exist. This passes in my CPython 2.7.9 environment. Here is the output
```
IronPython 2.7.5 (2.7.5.0) on .NET 4.0.30319.0 (32-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> try:
...     import http.client as httplib
... except ImportError:
...     pass
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
AttributeError: 'LightException' object has no attribute 'client'
```

**Comment by jdhardy** [comment] 2015-06-20 19:00
Duplicate of #1189.

**Closed by jdhardy** 2015-06-20 19:00 UTC
