### ISSUE TITLE
[ipy 2.7] warnings.catch_warnings does not work

### ISSUE THREAD

**Issue by mbuesch** [IronLanguages/main#197] opened 2014-05-13 08:17 UTC
```
IronPython 2.7.5b1 (2.7.0.40) on Mono 4.0.30319.17020 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> import warnings
>>> with warnings.catch_warnings():
...     warnings.simplefilter("ignore")
...     warnings.warn("xxx", DeprecationWarning)
... 
__main__:1: DeprecationWarning: xxx
>>> warnings.simplefilter("ignore")             
>>> warnings.warn("xxx", DeprecationWarning)    
>>> 
```

**Comment by slide** [comment] 2016-07-29 22:00
This is a duplicate of #631

**Closed by slide** 2016-07-29 22:00 UTC
Labels: untriaged
