### ISSUE TITLE
IronPython pdb does not add current working directory to sys.path

### ISSUE THREAD

**Issue by rmstoi** [IronLanguages/main#1225] opened 2015-09-02 16:09 UTC
I have a script that loads an assembly from the current working directory:

``` python
import clr
clr.AddReferenceToFile("Interop.Assembly")
```

The script works fine when run under ironpython. When I try to debug it with pdb I get an exception.

```
ipy -m pdb ./script.py
```

The exception is:

```
IOError: System.IO.IOException: Could not add reference to assembly Interop.Assembly
```

I can work around this by prepending this code before clr.AddReferenceToFile:

``` python
if "pdb" in sys.modules:
    sys.path.insert(0, os.getcwd())
```

Hence, the bug seems to be that under pdb sys.path lacks cwd.

**Comment by simplicbe** [comment] 2016-07-19 14:16
@rmstoi are you able to fix this issue?

**Comment by rmstoi** [comment] 2016-07-26 11:41
@simplicbe It looks that the issue is in clr module. Importing python modules from the current working directory works fine under pdb.

Unfortuanatelly I'm not able to fix this issue: insufficent Windows programming skills.

**Comment by slide** [comment] 2016-08-11 16:00
This is odd since the pdb module does this:

```python
sys.path[0] = os.path.dirname(mainpyfile)
```

**Comment by slide** [comment] 2016-11-10 13:12
I have a possible fix for this, but I need to make sure it doesn't break something else. I also want to understand why the issue is there.

**Comment by slide** [comment] 2017-06-09 15:23
This issue was moved to IronLanguages/ironpython2#115

**Closed by slide** 2017-06-09 15:23 UTC
